services:
  - type: web
    name: download-anything
    env: python
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
