services:
  - type: web
    name: download-anything
    env: python
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn app:app --timeout 300 --workers 1 --threads 2 --worker-class gthread"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
